apiVersion: v1
kind: Service
metadata:
  name: test-cluster
  namespace: test-cluster
spec:
  selector:
    app: test-cluster
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
    